language: python
python:
  - 2.7
  
notifications:
  email: false
  slack: slac-suncat:uMRwgQgYaSJFNr48PlZ1vtuf

env:
    matrix:
      - WITH_SCIPY=true
      - WITH_SCIPY=false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - if [ "x${WITH_SCIPY}" == "xtrue" ]; then conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose; else conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy matplotlib nose; fi
  - pip install mpmath
  - pip install ase coverage
  - python setup.py install #install catmap
 
# Run tests; this is a very crude way of testing things
# We should move to a more elegant strategy in the future
script:
  - coverage run --source=catmap -a test_dependencies.py
  - cd tutorials/1-generating_input_file
  - coverage run --source=catmap -a generate_input.py
  - cd ../2-creating_microkinetic_model
  - coverage run --source=catmap -a mkm_job.py
  - cd ../3-refining_microkinetic_model
  - coverage run --source=catmap -a mkm_job.py
  - cd ../thermodynamic_descriptors
  - coverage run --source=catmap -a mkm_job.py
  - cd ../output_variables
  - coverage run --source=catmap -a mkm_job.py
  - coverage run --source=catmap -a mkm_job_output_all.py
  - cd ../electrochemistry/HER
  - coverage run --source=catmap -a mkm_job.py
  - cd ../ORR_scaling
  - coverage run --source=catmap -a make_input.py
  - coverage run --source=catmap -a mkm_job.py
  - cd ../ORR_thermo
  - coverage run --source=catmap -a make_input.py
  - coverage run --source=catmap -a mkm_job.py
  - cd ../electrons
  - coverage run --source=catmap -a mkm_job.py
  - coverage report
